# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lBKzn2C4FPdvRwymQxUPtHcCxba7Ci07
"""

# If your file is not already in the left sidebar (/content), upload it now:
from google.colab import files
uploaded = files.upload()   # choose your Excel file

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Use the exact filename shown after upload in the output area
FILENAME = list(uploaded.keys())[0]     # auto-pick the uploaded file
df = pd.read_excel(FILENAME)

pd.set_option('display.max_colwidth', 200)

print(df.shape)
df.columns.to_list()


# Make machine-friendly names
clean = (df.columns
          .str.strip()
          .str.replace(r'\s+', ' ', regex=True)
          .str.replace(r'[^0-9a-zA-Z ]', '', regex=True)
          .str.lower()
          .str.replace(' ', '_'))

df.columns = clean
df.columns.to_list()


def find_col(keyword, required=True):
    hits = [c for c in df.columns if keyword in c]
    if not hits:
        if required:
            raise ValueError(f"Column containing '{keyword}' not found. Print df.columns to check.")
        return None
    return hits[0]

COL = {}
COL['timestamp']        = find_col('timestamp', required=False)
COL['region']           = find_col('region')
COL['turnover']         = find_col('turnover')
COL['employees']        = find_col('employees')
COL['years_oper']       = find_col('years_have_you_been_operating')
COL['main_activity']    = find_col('main_agro')
COL['trade_status']     = find_col('exporting_or_importing')
COL['uses_it']          = find_col('does_your_business_use_information_systems')  # yes/no
COL['it_years']         = find_col('how_long_have_you_been_integrating_information_technology')
COL['perf_before_it']   = find_col('financial_performance_of_your_business_before_using_it')
COL['it_help']          = find_col('how_much_do_you_think_it_helps', required=False)
COL['inv_tech']         = find_col('have_you_made_any_investments_in_technology', required=False)
COL['inv_what']         = find_col('if_yes_what_did_you_invest_in', required=False)
# Add more find_col(...) lines if you need more questions later

COL


# --- Turnover ranges (ALL) → numeric midpoints (in millions ALL)
turnover_map = {
    'up to 5 million all': 2.5,
    '5 to 8 million all': 6.5,
    '5-8 million all': 6.5,
    '8 to 10 million all': 9,
    '8-10 million all': 9,
    'over 10 million all': 12,
    '>10 million all': 12
}
df['turnover_num'] = df[COL['turnover']].str.lower().map(turnover_map)

# --- Employees → numeric midpoints
emp_map = {
    '1-4 employees': 2.5,
    '5-9 employees': 7,
    'over 10 employees': 12,
    '>10 employees': 12
}
df['employees_num'] = df[COL['employees']].str.lower().map(emp_map)

# --- Years operating → numeric midpoints
yrs_map = {
    '1-5 years': 3,
    '5-10 years': 7.5,
    'over 10 years': 12,
    '>10 years': 12
}
df['years_oper_num'] = df[COL['years_oper']].str.lower().map(yrs_map)

# --- Uses IT (Yes/No) → 1/0
yn_map = {'yes':1, 'no':0}
df['uses_it_bin'] = df[COL['uses_it']].str.lower().map(yn_map)

# --- IT years integrated → numeric
ityrs_map = {
    'less than 1 year': 0.5,
    'under 1 year': 0.5,
    '1 year': 1,
    '2 to 5 years': 3.5,
    '2-5 years': 3.5,
    'over 5 years': 6,
    '>5 years': 6
}
df['it_years_num'] = df[COL['it_years']].str.lower().map(ityrs_map)

# --- Financial performance BEFORE IT → ordered scale
perf_map = {
    'very low (loss)': 1,
    'low (some loss)': 2,
    'neutral': 3,
    'good': 4,
    'very good': 5
}
df['perf_before_it_num'] = df[COL['perf_before_it']].str.lower().map(perf_map)

# --- IT helps in daily activities (optional)
if COL['it_help']:
    help_map = {
        'very positively': 5,
        'positively': 4,
        'neutral': 3,
        'negatively': 2,
        'very negatively': 1
    }
    df['it_help_num'] = df[COL['it_help']].str.lower().map(help_map)

# --- Investment in technology (Yes/No)
if COL['inv_tech']:
    df['inv_tech_bin'] = df[COL['inv_tech']].str.lower().map(yn_map)

# --- Multi-select: what did you invest in? -> one-hot flags
if COL['inv_what']:
    inv = df[COL['inv_what']].fillna('').str.lower()
    for key in ['equipment','software','programming','information systems','systems','hardware']:
        df[f'inv_{key.replace(" ","_")}'] = inv.str.contains(key).astype(int)

df[['turnover_num','employees_num','years_oper_num','uses_it_bin','it_years_num','perf_before_it_num']].head()

df.isna().sum().sort_values(ascending=False).head(10)  # see missing values
df.describe(include='all')

# This is the corrected line that will now work
df.select_dtypes(include=np.number).describe()


# IT adoption rate
it_rate = df['uses_it_bin'].mean()*100
print(f"IT adoption rate: {it_rate:.1f}%")

# Average turnover by IT adoption
avg_turn = df.groupby('uses_it_bin')['turnover_num'].mean().rename({0:'No IT',1:'Uses IT'})
avg_turn

# First, we need to import the required library for statistical tests.
from scipy import stats

# Next, we'll import matplotlib for visualization and create a plot
import matplotlib.pyplot as plt
import seaborn as sns

# Let's perform a t-test to check for a significant difference
# in turnover between businesses that use IT and those that do not.

# Separate the turnover data into two groups based on the 'uses_it_bin' column.
it_users_turnover = df[df['uses_it_bin'] == 1]['turnover_num'].dropna()
non_it_users_turnover = df[df['uses_it_bin'] == 0]['turnover_num'].dropna()

# Perform the independent two-sample t-test.
# The `equal_var=False` argument is used because we cannot assume
# that the variances of the two groups are equal. This is the more
# robust option.
t_stat, p_value = stats.ttest_ind(it_users_turnover, non_it_users_turnover, equal_var=False)

# Print the results.
print("--- T-Test Results ---")
print(f"T-statistic: {t_stat:.2f}")
print(f"P-value: {p_value:.3f}")


# Now, let's create a box plot to visualize the difference in turnover
# between the two groups. This is a crucial chart for your thesis.
plt.style.use('seaborn-v0_8-whitegrid')
plt.figure(figsize=(8, 6))

sns.boxplot(x='uses_it_bin', y='turnover_num', data=df, palette='pastel')

# Let's make the chart more professional.
plt.title('Business Turnover by IT Adoption', fontsize=16, fontweight='bold')
plt.xlabel('IT Adoption', fontsize=12)
plt.ylabel('Turnover (in Millions ALL)', fontsize=12)
plt.xticks(ticks=[0, 1], labels=['No IT', 'Uses IT'], fontsize=10)

# Add a text annotation for the mean values to make the plot more informative.
# We'll use the 'groupby' data you created earlier.
avg_turn = df.groupby('uses_it_bin')['turnover_num'].mean().rename({0:'No IT',1:'Uses IT'})
plt.text(-0.25, avg_turn['No IT'] + 0.1, f"Mean: {avg_turn['No IT']:.2f}", ha='center', fontsize=10, color='black', fontweight='bold')
plt.text(0.75, avg_turn['Uses IT'] + 0.1, f"Mean: {avg_turn['Uses IT']:.2f}", ha='center', fontsize=10, color='black', fontweight='bold')

plt.tight_layout()
plt.show()

# As an extra step, we can create a histogram to compare
# the distribution of turnover for both groups side-by-side.
plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='turnover_num', hue='uses_it_bin', kde=True, bins=5, palette='pastel')
plt.title('Distribution of Turnover by IT Adoption', fontsize=16, fontweight='bold')
plt.xlabel('Turnover (in Millions ALL)', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.legend(title='IT Adoption', labels=['Uses IT', 'No IT'])
plt.show()

# 1. Data Loading and Preparation
# To prevent errors, please upload your file again.
from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

# Use the exact filename shown after upload in the output area
FILENAME = list(uploaded.keys())[0]
df = pd.read_excel(FILENAME)

pd.set_option('display.max_colwidth', 200)

print(f"Original DataFrame Shape: {df.shape}")
df.columns.to_list()


# 2. Data Cleaning and Transformation
clean = (df.columns
          .str.strip()
          .str.replace(r'\s+', ' ', regex=True)
          .str.replace(r'[^0-9a-zA-Z ]', '', regex=True)
          .str.lower()
          .str.replace(' ', '_'))

df.columns = clean

def find_col(keyword, required=True):
    hits = [c for c in df.columns if keyword in c]
    if not hits:
        if required:
            raise ValueError(f"Column containing '{keyword}' not found.")
        return None
    return hits[0]

COL = {
    'turnover': find_col('turnover'),
    'employees': find_col('employees'),
    'years_oper': find_col('years_have_you_been_operating'),
    'uses_it': find_col('does_your_business_use_information_systems'),
    'it_years': find_col('how_long_have_you_been_integrating_information_technology'),
    'perf_before_it': find_col('financial_performance_of_your_business_before_using_it'),
    'it_help': find_col('how_much_do_you_think_it_helps', required=False),
    'inv_tech': find_col('have_you_made_any_investments_in_technology', required=False)
}

# Mapping functions
turnover_map = {
    'up to 5 million all': 2.5, '5 to 8 million all': 6.5, '5-8 million all': 6.5,
    '8 to 10 million all': 9, '8-10 million all': 9, 'over 10 million all': 12, '>10 million all': 12
}
emp_map = {
    '1-4 employees': 2.5, '5-9 employees': 7, 'over 10 employees': 12, '>10 employees': 12
}
yrs_map = {
    '1-5 years': 3, '5-10 years': 7.5, 'over 10 years': 12, '>10 years': 12
}
yn_map = {'yes': 1, 'no': 0}
ityrs_map = {
    'less than 1 year': 0.5, 'under 1 year': 0.5, '1 year': 1,
    '2 to 5 years': 3.5, '2-5 years': 3.5, 'over 5 years': 6, '>5 years': 6
}
perf_map = {
    'very low (loss)': 1, 'low (some loss)': 2, 'neutral': 3, 'good': 4, 'very good': 5
}
help_map = {
    'very positively': 5, 'positively': 4, 'neutral': 3, 'negatively': 2, 'very negatively': 1
}

df['turnover_num'] = df[COL['turnover']].str.lower().map(turnover_map)
df['employees_num'] = df[COL['employees']].str.lower().map(emp_map)
df['years_oper_num'] = df[COL['years_oper']].str.lower().map(yrs_map)
df['uses_it_bin'] = df[COL['uses_it']].str.lower().map(yn_map)
df['it_years_num'] = df[COL['it_years']].str.lower().map(ityrs_map)
df['perf_before_it_num'] = df[COL['perf_before_it']].str.lower().map(perf_map)
if COL.get('it_help'):
    df['it_help_num'] = df[COL['it_help']].str.lower().map(help_map)

print("\n--- Descriptive Statistics for All Columns ---")
print(df.describe(include='all'))

print("\n--- Descriptive Statistics for Numeric Columns ---")
print(df.select_dtypes(include=np.number).describe())


# 3. Inferential Analysis: T-test for IT Adoption vs. Turnover
print("\n--- Inferential Analysis: T-test ---")
it_users_turnover = df[df['uses_it_bin'] == 1]['turnover_num'].dropna()
non_it_users_turnover = df[df['uses_it_bin'] == 0]['turnover_num'].dropna()

t_stat, p_value = stats.ttest_ind(it_users_turnover, non_it_users_turnover, equal_var=False)
print(f"T-statistic: {t_stat:.2f}")
print(f"P-value: {p_value:.3f}")


# 4. Data Visualization
print("\n--- Visualizations ---")
# Box Plot
plt.style.use('seaborn-v0_8-whitegrid')
plt.figure(figsize=(8, 6))
sns.boxplot(x='uses_it_bin', y='turnover_num', data=df, palette='pastel')
plt.title('Xhiro e Biznesit sipas Përshtatjes së IT-së', fontsize=16, fontweight='bold')
plt.xlabel('IT Adoption', fontsize=12)
plt.ylabel('Turnover (in Millions ALL)', fontsize=12)
plt.xticks(ticks=[0, 1], labels=['No IT', 'Uses IT'], fontsize=10)
avg_turn = df.groupby('uses_it_bin')['turnover_num'].mean().rename({0:'No IT', 1:'Uses IT'})
plt.text(-0.25, avg_turn['No IT'] + 0.1, f"Mean: {avg_turn['No IT']:.2f}", ha='center', fontsize=10, color='black', fontweight='bold')
plt.text(0.75, avg_turn['Uses IT'] + 0.1, f"Mean: {avg_turn['Uses IT']:.2f}", ha='center', fontsize=10, color='black', fontweight='bold')
plt.tight_layout()
plt.show()

# Histogram
plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='turnover_num', hue='uses_it_bin', kde=True, bins=5, palette='pastel')
plt.title('Shpërndarja e xhiros sipas përdorimit të IT-së', fontsize=16, fontweight='bold')
plt.xlabel('Turnover (in Millions ALL)', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.legend(title='IT Adoption', labels=['Uses IT', 'No IT'])
plt.show()


# 5. Correlation Analysis
print("\n--- Correlation Analysis ---")
numeric_cols = ['turnover_num', 'employees_num', 'years_oper_num',
                'it_years_num', 'perf_before_it_num', 'it_help_num']
correlation_matrix = df[numeric_cols].corr()

print("Correlation Matrix:")
print(correlation_matrix.round(2))

# Heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation Matrix of Key Numeric Variables', fontsize=16, fontweight='bold')
plt.show()

# Pairplot
sns.pairplot(df[numeric_cols].dropna())
plt.suptitle('Pairplot of Numeric Variables', y=1.02, fontsize=16, fontweight='bold')
plt.show()

import statsmodels.api as sm
import pandas as pd

# Define the dependent variable (Y) and the independent variables (X)
# We will use all the numeric columns we've cleaned as independent variables.
# The `it_help_num` has many missing values, so we'll drop them.
df_reg = df.dropna(subset=['turnover_num', 'employees_num', 'years_oper_num',
                          'it_years_num', 'perf_before_it_num', 'it_help_num',
                          'uses_it_bin'])

# Define the independent variables (X) and dependent variable (Y)
X = df_reg[['employees_num', 'years_oper_num', 'it_years_num', 'perf_before_it_num', 'it_help_num', 'uses_it_bin']]
Y = df_reg['turnover_num']

# Add a constant to the independent variable matrix for the intercept
X = sm.add_constant(X)

# Fit the regression model
model = sm.OLS(Y, X).fit()

# Print the summary of the regression results
print(model.summary())

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Assuming 'df' is your existing DataFrame
# Let's create a scatter plot of turnover versus employees
# with a regression line.
plt.style.use('seaborn-v0_8-whitegrid')
plt.figure(figsize=(10, 6))

sns.regplot(x='employees_num', y='turnover_num', data=df,
            scatter_kws={'alpha':0.8, 's':100},
            line_kws={'color':'red', 'linestyle':'--'})

plt.title('Xhiro vs Nr. punonjesve', fontsize=16, fontweight='bold')
plt.xlabel('Nr i punonjesve', fontsize=12)
plt.ylabel('Xhiro (in Millions ALL)', fontsize=12)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# The following two lines of code are for demonstration purposes only.
# You will need to replace this with your actual data from your thesis.
# For example, from a CSV or Excel file.
# We're creating some dummy data that looks similar to your graph.
employees = np.array([50, 75, 100, 125, 150, 175, 200, 225, 250, 275])
turnover = np.array([12, 18, 25, 30, 35, 42, 50, 55, 60, 68])

# We can add some random noise to make it more realistic.
np.random.seed(0)
turnover_with_noise = turnover + np.random.normal(0, 5, turnover.shape)

# Step 1: Create the scatter plot
plt.figure(figsize=(10, 6))
plt.scatter(employees, turnover_with_noise, color='blue', label='Actual Data Points')
plt.title('Xhiro vs Nr. i punonjesve')
plt.xlabel('Nr i pjnonjesve')
plt.ylabel('Xhiroja (%)')
plt.grid(True)

# Step 2: Calculate the regression line
# We'll use numpy's polyfit to find the best-fit line coefficients (slope and intercept).
# polyfit(x, y, degree)
slope, intercept = np.polyfit(employees, turnover_with_noise, 1)

# Step 3: Create the regression line for plotting
regression_line = slope * employees + intercept

# Step 4: Plot the regression line
plt.plot(employees, regression_line, color='red', linestyle='--', label='Regression Line')

# Step 5: Add a legend to explain what the plot elements are.
plt.legend()

# Step 6: Show the plot
plt.show()

# You can also print the equation of the line if you want to include it in your thesis.
print(f"The regression equation is: Turnover = {slope:.2f} * Employees + {intercept:.2f}")

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import statsmodels.api as sm

# Assuming 'df' is your existing DataFrame and you have already run the regression code
# 1. First, re-run the regression model to get the residuals
df_reg = df.dropna(subset=['turnover_num', 'employees_num', 'years_oper_num',
                          'it_years_num', 'perf_before_it_num', 'it_help_num',
                          'uses_it_bin'])
X = df_reg[['employees_num', 'years_oper_num', 'it_years_num', 'perf_before_it_num', 'it_help_num', 'uses_it_bin']]
Y = df_reg['turnover_num']
X = sm.add_constant(X)
model = sm.OLS(Y, X).fit()

# 2. Create the residual plot
plt.style.use('seaborn-v0_8-whitegrid')
plt.figure(figsize=(10, 6))

residuals = model.resid
fitted_values = model.fittedvalues

sns.scatterplot(x=fitted_values, y=residuals, color='blue')
plt.axhline(y=0, color='red', linestyle='--')

plt.title('Residual Plot', fontsize=16, fontweight='bold')
plt.xlabel('Fitted Values (Vlerat e Përshtatura)', fontsize=12)
plt.ylabel('Mbetjet', fontsize=12)
plt.show()
